---
# MAC to hostname mapping
mac_address_mapping:

  # Top Row
  # View 01
  "b8:27:eb:79:ba:7f":
    name: eye01

  # View 02
  "b8:27:eb:4e:68:96":
    name: eye02

  # View 03
  "b8:27:eb:bc:2a:e8":
    name: eye03

  # View 04
  #"b8:27:eb:cc:ba:8c":
  "b8:27:eb:5e:65:1f":
    name: eye04

  # View 05
  "b8:27:eb:67:f4:a0":
    name: eye05

  # View 06
  "b8:27:eb:89:9d:fd":
    name: eye06

  # Bottom Row
  # View 07
  "b8:27:eb:1d:c7:ce":
    name: eye07

  # View 08
  "b8:27:eb:a1:14:36":
    name: eye08

  # View 09
  "b8:27:eb:36:24:1a":
    name: eye09

  # ??
  # View 10
  "b8:27:eb:80:eb:8c":
    name: eye10

  # View 11
  #"b8:27:eb:b3:a5:3f":
  "b8:27:eb:cc:ba:8c":
    name: eye11

  # View 12
  "b8:27:eb:31:98:6a":
    name: eye12


  ## TESTING
  "b8:27:eb:9f:ab:2a":
    name: eye13

  "b8:27:eb:be:ae:35":
    name: eve


# Nameservers to use in resolv.conf.
dns_nameservers:
  - "10.0.0.1"
  - "8.8.4.4"

beholder_router:
  - "10.0.0.1"